// Code generated by protoc-gen-go. DO NOT EDIT.
// source: StoragedataInfo.proto

package Client

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// 定义一个新的对象
type MessagedataInfo_Request struct {
	LOperationTarget     int32    `protobuf:"varint,1,opt,name=lOperationTarget,proto3" json:"lOperationTarget,omitempty"`
	LOperationType       int32    `protobuf:"varint,2,opt,name=lOperationType,proto3" json:"lOperationType,omitempty"`
	BData                []byte   `protobuf:"bytes,3,opt,name=bData,proto3" json:"bData,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagedataInfo_Request) Reset()         { *m = MessagedataInfo_Request{} }
func (m *MessagedataInfo_Request) String() string { return proto.CompactTextString(m) }
func (*MessagedataInfo_Request) ProtoMessage()    {}
func (*MessagedataInfo_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_46f0e9ac62b0e46a, []int{0}
}

func (m *MessagedataInfo_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagedataInfo_Request.Unmarshal(m, b)
}
func (m *MessagedataInfo_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagedataInfo_Request.Marshal(b, m, deterministic)
}
func (m *MessagedataInfo_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagedataInfo_Request.Merge(m, src)
}
func (m *MessagedataInfo_Request) XXX_Size() int {
	return xxx_messageInfo_MessagedataInfo_Request.Size(m)
}
func (m *MessagedataInfo_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagedataInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_MessagedataInfo_Request proto.InternalMessageInfo

func (m *MessagedataInfo_Request) GetLOperationTarget() int32 {
	if m != nil {
		return m.LOperationTarget
	}
	return 0
}

func (m *MessagedataInfo_Request) GetLOperationType() int32 {
	if m != nil {
		return m.LOperationType
	}
	return 0
}

func (m *MessagedataInfo_Request) GetBData() []byte {
	if m != nil {
		return m.BData
	}
	return nil
}

type MessagedataInfo_Response struct {
	StrCode              string   `protobuf:"bytes,1,opt,name=strCode,proto3" json:"strCode,omitempty"`
	StrMsg               string   `protobuf:"bytes,2,opt,name=strMsg,proto3" json:"strMsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MessagedataInfo_Response) Reset()         { *m = MessagedataInfo_Response{} }
func (m *MessagedataInfo_Response) String() string { return proto.CompactTextString(m) }
func (*MessagedataInfo_Response) ProtoMessage()    {}
func (*MessagedataInfo_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_46f0e9ac62b0e46a, []int{1}
}

func (m *MessagedataInfo_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MessagedataInfo_Response.Unmarshal(m, b)
}
func (m *MessagedataInfo_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MessagedataInfo_Response.Marshal(b, m, deterministic)
}
func (m *MessagedataInfo_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MessagedataInfo_Response.Merge(m, src)
}
func (m *MessagedataInfo_Response) XXX_Size() int {
	return xxx_messageInfo_MessagedataInfo_Response.Size(m)
}
func (m *MessagedataInfo_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_MessagedataInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_MessagedataInfo_Response proto.InternalMessageInfo

func (m *MessagedataInfo_Response) GetStrCode() string {
	if m != nil {
		return m.StrCode
	}
	return ""
}

func (m *MessagedataInfo_Response) GetStrMsg() string {
	if m != nil {
		return m.StrMsg
	}
	return ""
}

func init() {
	proto.RegisterType((*MessagedataInfo_Request)(nil), "StorageService.MessagedataInfo_Request")
	proto.RegisterType((*MessagedataInfo_Response)(nil), "StorageService.MessagedataInfo_Response")
}

func init() { proto.RegisterFile("StoragedataInfo.proto", fileDescriptor_46f0e9ac62b0e46a) }

var fileDescriptor_46f0e9ac62b0e46a = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x0d, 0x2e, 0xc9, 0x2f,
	0x4a, 0x4c, 0x4f, 0x4d, 0x49, 0x2c, 0x49, 0xf4, 0xcc, 0x4b, 0xcb, 0xd7, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0x17, 0xe2, 0x83, 0x0a, 0x07, 0xa7, 0x16, 0x95, 0x65, 0x26, 0xa7, 0x2a, 0x35, 0x33, 0x72,
	0x89, 0xfb, 0xa6, 0x16, 0x17, 0x23, 0xa9, 0x8c, 0x0f, 0x4a, 0x2d, 0x2c, 0x4d, 0x2d, 0x2e, 0x11,
	0xd2, 0xe2, 0x12, 0xc8, 0xf1, 0x2f, 0x48, 0x2d, 0x4a, 0x2c, 0xc9, 0xcc, 0xcf, 0x0b, 0x49, 0x2c,
	0x4a, 0x4f, 0x2d, 0x91, 0x60, 0x54, 0x60, 0xd4, 0x60, 0x0d, 0xc2, 0x10, 0x17, 0x52, 0xe3, 0xe2,
	0x43, 0x12, 0xab, 0x2c, 0x48, 0x95, 0x60, 0x02, 0xab, 0x44, 0x13, 0x15, 0x12, 0xe1, 0x62, 0x4d,
	0x72, 0x49, 0x2c, 0x49, 0x94, 0x60, 0x56, 0x60, 0xd4, 0xe0, 0x09, 0x82, 0x70, 0x94, 0x7c, 0xb8,
	0x24, 0x30, 0x1d, 0x51, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc1, 0xc5, 0x5e, 0x5c, 0x52,
	0xe4, 0x9c, 0x9f, 0x92, 0x0a, 0xb6, 0x9c, 0x33, 0x08, 0xc6, 0x15, 0x12, 0xe3, 0x62, 0x2b, 0x2e,
	0x29, 0xf2, 0x2d, 0x4e, 0x07, 0xdb, 0xc5, 0x19, 0x04, 0xe5, 0x19, 0x55, 0x72, 0x71, 0x17, 0x43,
	0x7c, 0x09, 0x32, 0x49, 0x28, 0x8b, 0x4b, 0x38, 0xa0, 0xb4, 0x38, 0x03, 0x2d, 0x3c, 0x84, 0xd4,
	0xf5, 0x50, 0x83, 0x42, 0x0f, 0x47, 0x30, 0x48, 0x69, 0x10, 0x56, 0x08, 0x71, 0xaa, 0x12, 0x43,
	0x12, 0x1b, 0x38, 0x94, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xd3, 0x35, 0x92, 0x64, 0x7e,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// StorageInfoClient is the client API for StorageInfo service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StorageInfoClient interface {
	PushStoragedataInfo(ctx context.Context, in *MessagedataInfo_Request, opts ...grpc.CallOption) (*MessagedataInfo_Response, error)
}

type storageInfoClient struct {
	cc *grpc.ClientConn
}

func NewStorageInfoClient(cc *grpc.ClientConn) StorageInfoClient {
	return &storageInfoClient{cc}
}

func (c *storageInfoClient) PushStoragedataInfo(ctx context.Context, in *MessagedataInfo_Request, opts ...grpc.CallOption) (*MessagedataInfo_Response, error) {
	out := new(MessagedataInfo_Response)
	err := c.cc.Invoke(ctx, "/StorageService.storageInfo/PushStoragedataInfo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageInfoServer is the server API for StorageInfo service.
type StorageInfoServer interface {
	PushStoragedataInfo(context.Context, *MessagedataInfo_Request) (*MessagedataInfo_Response, error)
}

// UnimplementedStorageInfoServer can be embedded to have forward compatible implementations.
type UnimplementedStorageInfoServer struct {
}

func (*UnimplementedStorageInfoServer) PushStoragedataInfo(ctx context.Context, req *MessagedataInfo_Request) (*MessagedataInfo_Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PushStoragedataInfo not implemented")
}

func RegisterStorageInfoServer(s *grpc.Server, srv StorageInfoServer) {
	s.RegisterService(&_StorageInfo_serviceDesc, srv)
}

func _StorageInfo_PushStoragedataInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MessagedataInfo_Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageInfoServer).PushStoragedataInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/StorageService.storageInfo/PushStoragedataInfo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageInfoServer).PushStoragedataInfo(ctx, req.(*MessagedataInfo_Request))
	}
	return interceptor(ctx, in, info, handler)
}

var _StorageInfo_serviceDesc = grpc.ServiceDesc{
	ServiceName: "StorageService.storageInfo",
	HandlerType: (*StorageInfoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushStoragedataInfo",
			Handler:    _StorageInfo_PushStoragedataInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "StoragedataInfo.proto",
}
